export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const FETCH_REQUESTS_START = 'FETCH_REQUESTS_START';
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';
export const FETCH_REQUESTS_ERROR = 'FETCH_REQUESTS_ERROR';

export const FETCH_FIELDS = 'FETCH_FIELDS';
export const FETCH_FIELDS_START = 'FETCH_FIELDS_START';
export const FETCH_FIELDS_SUCCESS = 'FETCH_FIELDS_SUCCESS';
export const FETCH_FIELDS_ERROR = 'FETCH_FIELDS_ERROR';

export const UPDATE_FIELD_START = 'UPDATE_FIELD_START';
export const UPDATE_FIELD_SUCCESS = 'UPDATE_FIELD_SUCCESS';
export const UPDATE_FIELD_ERROR = 'UPDATE_FIELD_ERROR';
